#!/bin/sh
#
# Copyright 2019-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

set -ue

# test a an image by awaiting its HEALTHCHECK

docker_image=${1?docker_image is required, notably without a tag. Ex openzipkin/zipkin}
# This just makes sure containers run and the HEALTHCHECK works (for now..)
docker_compose_file=${2:-build-bin/docker-compose-$(echo ${docker_image}| cut -f2 -d/).yml}
docker_container=${3:-sut}

health_rc=0
if test -f "${docker_compose_file}"; then
  docker-compose -f "${docker_compose_file}" up --remove-orphans -d --quiet-pull || health_rc=1
else
  docker run --name ${docker_container} -d ${docker_image}:test || health_rc=1
fi

# This will fail if the container isn't healthy or doesn't exist (ex compose failed before creation)
if [ "${health_rc}" = "1" ] || ! build-bin/docker/docker_block_on_health ${docker_container}; then
  >&2 echo "*** Failed waiting for health of ${docker_container}"
  docker inspect --format='{{json .State.Health.Log}}' ${docker_container} || true
  if test -f "${docker_compose_file}"; then
    docker-compose -f "${docker_compose_file}" logs
  else
    docker logs ${docker_container} || true
  fi
  health_rc=1
fi

if test -f "${docker_compose_file}"; then
  docker-compose -f "${docker_compose_file}" down
else
  docker kill ${docker_container} && docker rm ${docker_container}
fi

exit ${health_rc}

