# Run `travis lint` when changing this file to avoid breaking the build.

# We need a full VM so that testcontainers can use Docker
# See https://docs.travis-ci.com/user/reference/overview/#for-a-particular-travisyml-configuration
arch: amd64           # arm64 is LXD containers which we can't use because we run Docker tests
os: linux             # required for arch different than amd64
dist: focal           # newest available distribution

services:
  - docker

# Credentials entered into https://travis-ci.org/github/openzipkin/${REPO}/settings are access
# controlled by branch (typically only master). Check to see if a well-known env is available
# before attempting to log in.
before_install:
  - |
    if [[ -n "$GH_USER" ]]; then
      # re-use this condition to control if we prepare Docker for multi-arch
      build-bin/setup_multiarch_docker

      # Log in to Docker Hub for releasing the image
      echo "$GH_TOKEN"| docker login ghcr.io -u "$GH_USER" --password-stdin
    fi

script: ./travis/publish.sh

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/9f1ee2f315d32956f8d6
    on_success: change
    on_failure: always

# When Travis, add to https://travis-ci.org/github/openzipkin/${REPO}/settings
#
# GH_TOKEN=XXX-https://github.com/settings/tokens-XXX
#   - makes release commits and tags, also writes to GHCR if Docker
#   - needs repo:status, public_repo and if Docker write:packages, delete:packages
#   - referenced in .settings.xml
#   - store like this: echo "https://$GH_TOKEN:@github.com" > .git/credentials
# GH_USER=user_that_created_GH_TOKEN