# permit depends_on/condition: service_healthy
version: '2.4'

services:
  eureka:
    image: ghcr.io/openzipkin/zipkin-eureka
    container_name: eureka
# Uncomment to require authentication
#    environment:
#      - EUREKA_USERNAME=username
#      - EUREKA_PASSWORD=password
# Uncomment to expose the eureka port for testing
#    ports:
#      - 8761:8761

  zipkin:
    extends:
      file: docker-compose.yml
      service: zipkin
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761/eureka/v2
      - EUREKA_HOSTNAME=zipkin
# Uncomment to authenticate eureka
#      - EUREKA_SERVICE_URL=http://username:password@eureka:8761/eureka/v2
    depends_on:
      eureka:
        condition: service_healthy

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761/eureka/v2
# Uncomment to authenticate eureka
#      - EUREKA_SERVICE_URL=http://username:password@eureka:8761/eureka/v2
    ports:
      - 8081:8081
    depends_on:
      backend:
        condition: service_healthy
      eureka:
        condition: service_healthy

  backend:
    extends:
      file: docker-compose.yml
      service: backend
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761/eureka/v2
# Uncomment to authenticate eureka
#      - EUREKA_SERVICE_URL=http://username:password@eureka:8761/eureka/v2
    depends_on:
      eureka:
        condition: service_healthy
