# Format version 2.1 was introduced with Docker Compose v1.9
# We need Docker Compose v1.9+ for unset variable interpolation
version: "2.1"

services:
  # Generate traffic by hitting http://localhost:8081
  frontend:
    container_name: frontend
    image: ghcr.io/openzipkin/brave-example:${PROJECT:-armeria}
    command: frontend
    ports:
      - 8081:8081
    depends_on:
      - backend
      - zipkin
  # Serves the /api endpoint the frontend uses
  backend:
    container_name: backend
    image: ghcr.io/openzipkin/brave-example:${PROJECT:-armeria}
    command: backend
    depends_on:
      - zipkin
  # View traces at http://127.0.0.1:9411/zipkin
  zipkin:
    image: openzipkin/zipkin-slim
    container_name: zipkin
    ports:
      - 9411:9411
