---
# Format version 2.1 was introduced with Docker Compose v1.9
# We need Docker Compose v1.9+ for unset variable interpolation
version: "2.1"

services:
  kafka:
    image: ghcr.io/openzipkin/zipkin-kafka
    container_name: kafka
    ports:
      - 2181:2181
      - 19092:19092
  kafka-topics:
    image: ghcr.io/openzipkin/zipkin-kafka
    container_name: kafka-topics
    entrypoint: "sh -c"
    command: "
      \"/kafka/bin/kafka-run-class.sh kafka.admin.TopicCommand --bootstrap-server kafka:9092 --create --topic input --partitions 2 --replication-factor 1 --if-not-exists
      &&
      /kafka/bin/kafka-run-class.sh kafka.admin.TopicCommand --bootstrap-server kafka:9092 --create --topic output --partitions 2 --replication-factor 1 --if-not-exists\"
      "
    depends_on:
      kafka:
        condition: service_healthy
