#!/bin/sh -ue

# This script sets up anything needed for `./deploy`. Do not assume `configure_test` was called.
#
# See [README.md] for an explanation of this and how CI should use it.
build-bin/docker/configure_docker_push

# We prime the Maven repository in CI, so that it can cache it between runs
MAVEN_PROJECT_BASEDIR=${1:-armeria} build-bin/maven/maven_go_offline -Dmaven.repo.local=${PWD}/m2repository
