#!/bin/sh -ue

# This script sets up anything needed for `./test`. This should not login to anything, as that
# should be done in `configure_deploy`.
#
# See [README.md] for an explanation of this and how CI should use it.
build-bin/docker/configure_docker

# We prime the Maven repository in CI, so that it can cache it between runs
MAVEN_PROJECT_BASEDIR=${1:-armeria} build-bin/maven/maven_go_offline -Dmaven.repo.local=${PWD}/m2repository
