# permit depends_on/condition: service_healthy
version: "2.4"

services:
  sut:
    container_name: sut
    image: ghcr.io/openzipkin/alpine:3.12.3
    entrypoint: /bin/sh
    # Keep the container running until HEALTHCHECK passes
    command: "-c \"sleep 5m\""
    healthcheck:
      # Return 0 when we can read back our trace ID
      test: wget -qO- --spider http://zipkin:9411/api/v2/trace/cafebabecafebabe
    depends_on:
      get_frontend:
        condition: service_started
  get_frontend:
    container_name: get_frontend
    image: ghcr.io/openzipkin/alpine:3.12.3
    entrypoint: /bin/sh
    # Pass a trace header with a constant trace ID, so that we know what to look for later
    command: "-c \"wget -qO- --header 'b3: cafebabecafebabe-cafebabecafebabe-1' http://frontend:8081\""
    depends_on:
      frontend:
        condition: service_healthy
      zipkin:
        condition: service_healthy
  frontend:
    container_name: frontend
    image: ${DOCKER_IMAGE}
    entrypoint: start-frontend
    depends_on:
      backend:
        condition: service_healthy
      zipkin:
        condition: service_started
  backend:
    container_name: backend
    image: ${DOCKER_IMAGE}
    entrypoint: start-backend
    depends_on:
      zipkin:
        condition: service_started
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim
    container_name: zipkin
