# permit depends_on/condition: service_healthy
version: '2.4'

# This configures examples so that they use Kafka to communicate.
services:
  sut:
    extends:
      file: docker-compose.base.yml
      service: sut
    depends_on:
      get_frontend:
        condition: service_started

  get_frontend:
    extends:
      file: docker-compose.base.yml
      service: get_frontend
    depends_on:
      frontend:
        condition: service_healthy

  frontend:
    extends:
      file: docker-compose.base.yml
      service: frontend
    environment:
      - EUREKA_SERVICE_URL=http://testuser:testpass@kafka:8761/kafka/v2
    depends_on:
      backend:
        condition: service_healthy

  backend:
    extends:
      file: docker-compose.base.yml
      service: backend
    environment:
      - EUREKA_SERVICE_URL=http://testuser:testpass@kafka:8761/kafka/v2
    depends_on:
      zipkin:
        condition: service_healthy
      kafka:
        condition: service_healthy

  zipkin:
    extends:
      file: docker-compose.base.yml
      service: zipkin

  kafka:
    image: ghcr.io/openzipkin/zipkin-kafka
    container_name: kafka
