# permit depends_on/condition: service_healthy
version: '2.4'

# This configures examples so that they use Eureka to discover the Zipkin
# endpoint.
services:
  sut:
    extends:
      file: docker-compose.base.yml
      service: sut
    depends_on:
      get_frontend:
        condition: service_started

  get_frontend:
    extends:
      file: docker-compose.base.yml
      service: get_frontend
    depends_on:
      frontend:
        condition: service_healthy

  frontend:
    extends:
      file: docker-compose.base.yml
      service: frontend
    environment:
      - EUREKA_SERVICE_URL=http://testuser:testpass@eureka:8761/eureka/v2
    depends_on:
      backend:
        condition: service_healthy

  backend:
    extends:
      file: docker-compose.base.yml
      service: backend
    environment:
      - EUREKA_SERVICE_URL=http://testuser:testpass@eureka:8761/eureka/v2
    depends_on:
      zipkin:
        condition: service_healthy
      eureka:
        condition: service_healthy

  zipkin:
    extends:
      file: docker-compose.base.yml
      service: zipkin
    environment:
      - EUREKA_SERVICE_URL=http://testuser:testpass@eureka:8761/eureka/v2
      - EUREKA_HOSTNAME=zipkin
    depends_on:
      eureka:
        condition: service_healthy

  eureka:
    image: ghcr.io/openzipkin/zipkin-eureka
    container_name: eureka
    environment:
      - EUREKA_USERNAME=testuser
      - EUREKA_PASSWORD=testpass

