#!/bin/sh -ue

POM="${VERSION}/pom.xml"
if [ -f "${POM}" ]; then
  JRE_VERSION=$(sed -n 's/.*<jre.version>\(.*\)<\/jre.version>.*/\1/p' "${POM}")
else
  echo "Expected ${POM} to exist"
  exit 1
fi

JAVA_VERSION=${JAVA_VERSION:-15.0.1_p9}
# DOCKER_ARCHS to eventually push to the registry
DOCKER_ARCHS="amd64 arm64"

case "${JRE_VERSION}" in
  6 )
    DOCKER_PARENT_IMAGE=ghcr.io/openzipkin/java:1.6.0-119
    # single arch image
    DOCKER_ARCHS=amd64
    ;;
  7 )
    DOCKER_PARENT_IMAGE=ghcr.io/openzipkin/java:1.7.0_285
    # single arch image
    DOCKER_ARCHS=amd64
    ;;
  8 )
    DOCKER_PARENT_IMAGE=ghcr.io/openzipkin/java:8.272.10-jre
    ;;
  11 )
    DOCKER_PARENT_IMAGE=ghcr.io/openzipkin/java:11.0.9_p11-jre
    ;;
  15 )
    DOCKER_PARENT_IMAGE=ghcr.io/openzipkin/java:15.0.1_p9-jre
    ;;
  * )
    echo "Invalid JRE_VERSION: ${JRE_VERSION}"
    exit 1
esac

export DOCKER_PARENT_IMAGE DOCKER_ARCHS
