# permit depends_on/condition: service_healthy
version: "2.4"

services:
  sut:
    container_name: sut
    image: ghcr.io/openzipkin/alpine:3.12.1
    entrypoint: /bin/sh
    # Keep the container running until HEALTHCHECK passes
    command: "-c \"sleep 5m\""
    healthcheck:
      # Return 0 when we can read back our trace ID
      test: wget -qO- --spider http://zipkin:9411/api/v2/trace/cafebabecafebabe
    depends_on:
      get_frontend:
        condition: service_started
  get_frontend:
    container_name: get_frontend
    image: ghcr.io/openzipkin/alpine:3.12.1
    entrypoint: /bin/sh
    # Pass a trace header with a constant trace ID, so that we know what to look for later
    command: "-c \"wget -qO- --header 'b3: cafebabecafebabe-cafebabecafebabe-1' http://frontend:8081\""
    depends_on:
      frontend:
        condition: service_healthy
      zipkin:
        condition: service_healthy
  frontend:
    container_name: frontend
    image: ${DOCKER_IMAGE}
    entrypoint: start-frontend
    depends_on:
      backend:
        condition: service_healthy
      zipkin:
        condition: service_started
  backend:
    container_name: backend
    image: ${DOCKER_IMAGE}
    entrypoint: start-backend
    depends_on:
      zipkin:
        condition: service_started

  kafka-zookeeper:
    image: ghcr.io/openzipkin/zipkin-kafka:${TAG:-latest}
    container_name: kafka-zookeeper
      # If using docker machine, uncomment the below and set your bootstrap
      # server list to 192.168.99.100:19092
      # environment:
    # - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
    ports:
      # Processes on the Docker host can set bootstrap server list to localhost:19092
      - 19092:19092

  zipkin:
    extends:
      file: docker-compose.test.yml
      service: zipkin
    # slim doesn't include Kafka support, so switch to the larger image
    image: ghcr.io/openzipkin/zipkin:${TAG:-latest}
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-zookeeper:9092
    depends_on:
      - kafka-zookeeper
