# permit depends_on/condition: service_healthy
version: "2.4"

services:
  frontend:
    container_name: frontend
    image: openzipkin/brave-example:${VERSION}-test
    entrypoint: start-frontend
    healthcheck:
      test: docker-healthcheck && ${TEST:-wget -qO- http://localhost:8081}
    depends_on:
      backend:
        condition: service_healthy
      zipkin:
        condition: service_healthy
  backend:
    container_name: backend
    image: openzipkin/brave-example:${VERSION}-test
    entrypoint: start-backend
    depends_on:
      zipkin:
        condition: service_healthy
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim
    container_name: zipkin
