services:
  sut:
    extends:
      file: docker-compose.base.yml
      service: sut
    depends_on:
      get_frontend:
        condition: service_started

  get_frontend:
    extends:
      file: docker-compose.base.yml
      service: get_frontend
    depends_on:
      frontend:
        condition: service_healthy

  frontend:
    extends:
      file: docker-compose.base.yml
      service: frontend
    depends_on:
      backend:
        condition: service_healthy

  backend:
    extends:
      file: docker-compose.base.yml
      service: backend
    depends_on:
      zipkin:
        condition: service_healthy

  zipkin:
    extends:
      file: docker-compose.base.yml
      service: zipkin


