#!/bin/sh

set -ue

# This script runs the tests of the project.
#
# See [README.md] for an explanation of this and how CI should use it.

export VERSION=${1:-armeria}
. $(dirname "$0")/docker_args
export DOCKER_IMAGE=openzipkin/brave-example:${VERSION}-test

echo "Building Docker image ${DOCKER_IMAGE}..."
build-bin/docker/docker_build ${DOCKER_IMAGE} ${VERSION}

echo "Verifying Docker image ${DOCKER_IMAGE}..."
# This just makes sure containers run and the HEALTHCHECK works (for now..)
docker-compose -f build-bin/docker-compose.test.yml up -d --quiet-pull
if build-bin/docker/block_on_health frontend; then
  health_rc=0
else
  health_rc=1
  docker logs frontend
fi
docker-compose -f build-bin/docker-compose.test.yml down
exit $health_rc