#!/bin/sh -v

if [[ "$DOCKER_REPO" == "index.docker.io/openzipkin/example-brave" ]]; then
  ALL_EXAMPLES=$(sed -n '/^ARG all_examples/s/.*"\(.*\)"/\1/gp' "$DOCKERFILE_PATH")

  for target in ${ALL_EXAMPLES}; do
    docker push "openzipkin/example-brave:${target}"
  done
fi
