#!/bin/sh -v

# Override push to avoid pushing a latest tag. We use tags for each example.
if [ "$DOCKER_REPO" = "index.docker.io/openzipkin/example-brave" ]; then
  ALL_PROJECTS=$(cd ../; ls */pom.xml |sed 's~/pom.xml~~g')

  for PROJECT in ${ALL_PROJECTS}; do
    docker push "openzipkin/example-brave:${PROJECT}"
  done
fi
