#!/bin/sh -v

# Override push to avoid pushing a latest tag. We use tags for each example.
if [ "$DOCKER_REPO" = "index.docker.io/openzipkin/example-brave" ]; then
  ALL_EXAMPLES=$(cd ../; ls */pom.xml|sed 's~/pom.xml~~g')

  for target in ${ALL_EXAMPLES}; do
    docker push "openzipkin/example-brave:${target}"
  done
fi
