# yamllint --format github .github/workflows/deploy.yml
---
name: deploy

on:
  # We deploy non-tagged pushes to master that aren't deploy documentation-only commits.
  push:
    tags: ''
    branches: master
    paths-ignore: '**/*.md'

jobs:
  discover-versions:
    name: Build version matrix
    runs-on: ubuntu-20.04  # newest available distribution, aka focal
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - id: set-matrix
        name: Generate outputs.matrix from pom.xml listing
        run: echo "::set-output name=matrix::{\"include\":$(.github/workflows/versions-as-json)}"
  test:
    runs-on: ubuntu-20.04  # newest available distribution, aka focal
    needs: discover-versions
    strategy:
      matrix: ${{ fromJson(needs.discover-versions.outputs.matrix) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ./m2repository  # Shared with the Docker build context via .dockerignore
          key: ${{ runner.os }}-${{ matrix.version }}-maven-${{ hashFiles('parent-pom.xml', format('{0}/pom.xml', matrix.version)) }}
          restore-keys: ${{ runner.os }}-${{ matrix.version }}-maven-
      # We can't cache Docker without using buildx because GH actions restricts /var/lib/docker
      # That's ok because DOCKER_PARENT_IMAGE is always ghcr.io and local anyway.
      - name: Deploy ${{ matrix.version }}
        env:
          # GH_USER=<user that created GH_TOKEN>
          GH_USER: ${{ secrets.GH_USER }}
          # GH_TOKEN=<hex token value>
          #   - pushes Docker images to ghcr.io
          #   - create via https://github.com/settings/tokens
          #   - needs repo:status, public_repo, write:packages, delete:packages
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          build-bin/configure_deploy ${{ matrix.version }} &&
          build-bin/deploy ${{ matrix.version }}
