# yamllint --format github .github/workflows/deploy.yml
---
name: deploy jersey2-cassandra3

on:
  # We deploy non-tagged pushes to master relevant for this project. We can't opt out of
  # documentation-only commits because GH actions does not permit paths and paths-ignore.
  push:
    tags: ''
    branches: master
    paths:
      - "build-bin/**"
      - "docker/**"
      - "jersey2-cassandra3/**"
      - ".github/workflows/deploy-jersey2-cassandra3.yaml"
      - "parent-pom.xml"

jobs:
  deploy:
    runs-on: ubuntu-20.04  # newest available distribution, aka focal
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ./m2repository  # Shared with the Docker build context via .dockerignore
          key: ${{ runner.os }}-jersey2-cassandra3-maven-${{ hashFiles('parent-pom.xml', 'jersey2-cassandra3/pom.xml') }}
          restore-keys: ${{ runner.os }}-jersey2-cassandra3-maven-
      # We can't cache Docker without using buildx because GH actions restricts /var/lib/docker
      # That's ok because DOCKER_PARENT_IMAGE is always ghcr.io and local anyway.
      - name: Deploy jersey2-cassandra3
        env:
          # GH_USER=<user that created GH_TOKEN>
          GH_USER: ${{ secrets.GH_USER }}
          # GH_TOKEN=<hex token value>
          #   - pushes Docker images to ghcr.io
          #   - create via https://github.com/settings/tokens
          #   - needs repo:status, public_repo, write:packages, delete:packages
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          build-bin/configure_deploy jersey2-cassandra3 &&
          build-bin/deploy jersey2-cassandra3
