# yamllint --format github .github/workflows/test.yml
---
name: test jersey2-cassandra3

on:
  # We deploy non-tagged pushes to master relevant for this project. We can't opt out of
  # documentation-only commits because GH actions does not permit paths and paths-ignore.
  pull_request:
    branches: master
    paths:
      - "build-bin/**"
      - "docker/**"
      - "jersey2-cassandra3/**"
      - ".github/workflows/test-jersey2-cassandra3.yaml"
      - "parent-pom.xml"

jobs:
  test:
    runs-on: ubuntu-22.04  # newest available distribution, aka jellyfish
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ./m2repository  # Shared with the Docker build context via .dockerignore
          key: ${{ runner.os }}-jersey2-cassandra3-maven-${{ hashFiles('parent-pom.xml', 'jersey2-cassandra3/pom.xml') }}
          restore-keys: ${{ runner.os }}-jersey2-cassandra3-maven-
      # Don't attempt to cache Docker. Sensitive information can be stolen
      # via forks, and login session ends up in ~/.docker. This is ok because
      # we publish DOCKER_PARENT_IMAGE to ghcr.io, hence local to the runner.
      - name: Test jersey2-cassandra3
        run: |
          build-bin/configure_test jersey2-cassandra3 &&
          build-bin/test jersey2-cassandra3
