# yamllint --format github .github/workflows/test.yml
---
name: test netty4-grpc

on:
  # We deploy non-tagged pushes to master relevant for this project. We can't opt out of
  # documentation-only commits because GH actions does not permit paths and paths-ignore.
  pull_request:
    branches: master
    paths:
      - "build-bin/**"
      - "docker/**"
      - "netty4-grpc/**"
      - ".github/workflows/test-netty4-grpc.yaml"
      - "parent-pom.xml"

jobs:
  test:
    runs-on: ubuntu-22.04  # newest available distribution, aka jellyfish
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ./m2repository  # Shared with the Docker build context via .dockerignore
          key: ${{ runner.os }}-netty4-grpc-maven-${{ hashFiles('parent-pom.xml', 'netty4-grpc/pom.xml') }}
          restore-keys: ${{ runner.os }}-netty4-grpc-maven-
      # Don't attempt to cache Docker. Sensitive information can be stolen
      # via forks, and login session ends up in ~/.docker. This is ok because
      # we publish DOCKER_PARENT_IMAGE to ghcr.io, hence local to the runner.
      - name: Test netty4-grpc
        run: |
          build-bin/configure_test netty4-grpc &&
          build-bin/test netty4-grpc
